resources:
  # Specify the pipelines that should cause this pipeline to be queued.
  pipelines:
    # Queue this pipeline whenever the ADU Gen 1 GitHub repro is updated
    - pipeline: azure_adu_private_preview
      source: Azure.iot-hub-device-update-yocto
      timeoutInMinutes: 1200
      trigger:
        branches:
          include:
            - develop

jobs:
- job: Build
  displayName: "Build Yocto Image"
  steps: 
    - bash: |
        echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
        ./scripts/install-deps.sh
      displayName: Install dependencies for Yocto Build
      workingDirectory: "$(Build.SourcesDirectory)"
      failOnStderr: true

    - bash: |
        echo Cloning poky, branch $(yocto_release)
        echo Cloning meta-raspberrypi, branch $(yocto_release)
        echo Cloning meta-azure-device-update, branch $(yocto_release)
        git clone --depth 1 --branch $(yocto_release) git://git.yoctoproject.org/poky
      displayName: "Clone poky $(yocto_release)"
      workingDirectory: "$(Build.SourcesDirectory)/yocto"

    - bash: |
        echo Cloning meta-swupdate, branch $(yocto_release)
        git clone --depth 1 --branch $(yocto_release)  https://github.com/sbabic/meta-swupdate
        git -C meta-swupdate rev-parse --abbrev-ref HEAD
        git -C meta-swupdate rev-parse HEAD
      displayName: "Clone meta-swupdate"
      workingDirectory: "$(Build.SourcesDirectory)/yocto"

    - bash: |
        echo Cloning meta-openembedded, branch $(yocto_release)
        git clone --depth 1 --branch $(yocto_release)  git://git.openembedded.org/meta-openembedded
        git -C meta-openembedded rev-parse --abbrev-ref HEAD
        git -C meta-openembedded rev-parse HEAD
      displayName: "Clone meta-openembedded"
      workingDirectory: "$(Build.SourcesDirectory)/yocto"

    - bash: |
        echo Cloning meta-raspberrypi, branch $(yocto_release)
        git clone --depth 1 --branch $(yocto_release)  git://git.yoctoproject.org/meta-raspberrypi
        git -C meta-raspberrypi rev-parse --abbrev-ref HEAD
        git -C meta-raspberrypi rev-parse HEAD
      displayName: "Clone meta-raspberrypi"
      workingDirectory: "$(Build.SourcesDirectory)/yocto"

    - bash: |
        echo Cloning meta-azure-device-update, branch $(yocto_release)
        git clone --depth 1 --branch $(yocto_release)  https://github.com/azure/meta-azure-device-update
        git -C meta-azure-device-update rev-parse --abbrev-ref HEAD
        git -C meta-azure-device-update rev-parse HEAD
      displayName: "Clone meta-azure-device-update"
      workingDirectory: "$(Build.SourcesDirectory)/yocto"

    - bash: |
        echo Cloning meta-azure-device-update-delta, branch $(yocto_release)
        git clone --depth 1 --branch $(yocto_release)  https://github.com/azure/meta-iot-hub-device-update-delta
        git -C meta-iot-hub-device-update-delta rev-parse --abbrev-ref HEAD
        git -C meta-iot-hub-device-update-delta rev-parse HEAD
      displayName: "Clone meta-iot-hub-device-update-delta"
      workingDirectory: "$(Build.SourcesDirectory)/yocto"

    - bash: |
        echo Cloning meta-raspberrypi-adu, branch $(yocto_release)
        git clone --depth 1 --branch $(yocto_release)  https://github.com/azure/meta-raspberrypi-adu
        git -C meta-raspberrypi-adu rev-parse --abbrev-ref HEAD
        git -C meta-raspberrypi-adu rev-parse HEAD
      displayName: "Clone meta-raspberrypi-adu"
      workingDirectory: "$(Build.SourcesDirectory)/yocto"
      
    - task: Bash@3
      displayName: "Yocto build - $(Build.BuildNumber), Gen $(adu_generation) | ADU $(adu_git_branch) : $(adu_git_commit) | DO $(do_git_branch) : $(do_git_commit) | ADU Delta $(adu_delta_git_branch) : $(adu_delta_git_commit)"
      inputs:
        targetType: "filePath"
        filePath: "./scripts/build.sh"
        arguments: '-c -t MinSizeRel -v $(Build.BuildNumber) --adu-generation $(adu_generation) --adu-src-uri $(adu_src_uri) --adu-git-branch $(adu_git_branch) --adu-git-commit $(adu_git_commit) --do-src-uri $(do_src_uri) --do-git-branch $(do_git_branch) --do-git-commit $(do_git_commit) --adu-delta-src-uri $(adu_delta_src_uri) --adu-delta-git-branch $(adu_delta_git_branch) --adu-delta-git-commit $(adu_delta_git_commit) -o $(Build.BinariesDirectory)'
        workingDirectory: $(Build.SourcesDirectory)

    # Copy artifacts to a staging directory for publishing.
    # there's something you can do here to get the outputs to take care of it
    - bash: |
        cp $(Build.BinariesDirectory)/build/tmp/deploy/images/raspberrypi4/adu-base-image-raspberrypi4.wic.gz \
          $(Build.ArtifactStagingDirectory)/adu-base-image-raspberrypi4-$(Build.BuildNumber).wic.gz
        cp $(Build.BinariesDirectory)/build/tmp/deploy/images/raspberrypi4/adu-update-image-raspberrypi4.swu \
          $(Build.ArtifactStagingDirectory)/adu-update-image-raspberrypi4-$(Build.BuildNumber).swu
      workingDirectory: $(Build.ArtifactStagingDirectory)
      displayName: "Stage build artifacts"
      failOnStderr: true

    - task: PublishBuildArtifacts@1
      displayName: "Publish images"
      inputs:
        ArtifactName: images
        PathtoPublish: "$(Build.ArtifactStagingDirectory)/images"

    - task: PublishBuildArtifacts@1
      displayName: "Publish binaries"
      inputs:
        ArtifactName: binaries
        PathtoPublish: "$(Build.ArtifactStagingDirectory)/bin"

