resources:
  # Specify the pipelines that should cause this pipeline to be queued.
  pipelines:
    # Queue this pipeline whenever the ADU private-preview repo is changed.
    - pipeline: azure_adu_private_preview
      source: Azure.iot-hub-device-update
      trigger:
        branches:
          include:
            - develop

# reuse jobs from build-template.yml
jobs:
  - template: build-template.yml
