header:
  version: 14
  includes: []

machine: qemuarm64

distro: poky

defaults:
  repos:
    branch: scarthgap

repos:
  poky:
    path: ../poky
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    path: ../meta-openembedded
    layers:
      meta-oe:
      meta-multimedia:
      meta-networking:
      meta-python:

  meta-clang:
    path: ../meta-clang

  meta-swupdate:
    path: ../meta-swupdate

  meta-azure-device-update:
    path: ../meta-azure-device-update

local_conf_header:
  base: |
    DISTRO_FEATURES:append = " systemd usrmerge"
    DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
    VIRTUAL-RUNTIME_init_manager = "systemd"
    VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
    PACKAGE_CLASSES ?= "package_ipk"
    EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
    USER_CLASSES ?= "buildstats"
    PATCHRESOLVE = "noop"
    CONF_VERSION = "2"
  cache: |
    DL_DIR ?= "${TOPDIR}/../downloads"
    SSTATE_DIR ?= "${TOPDIR}/../sstate-cache"
  parallel: |
    BB_NUMBER_THREADS ?= "14"
    PARALLEL_MAKE ?= "-j 14"
